#!/bin/sh

if [ "$#" -ge 1 ]; then
  VVERBOSE=true QUEUE=$1 rake environment resque:work
else
  VVERBOSE=true QUEUE=imports,exports,users,user_dbs,geocodings,synchronizations,tracker,user_migrations rake environment resque:work
fi
